name: cd

on:
  push:
    branches: main

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Enable tmate debug"
        type: boolean
        default: "false"

jobs:
  deploy-service:
    uses: octue/workflows/.github/workflows/deploy-cloud-run-service.yml@main
    with:
      gcp_project_name: windeurope72-private
      gcp_project_number: 406572174402
      gcp_region: europe-west1
      gcp_resource_affix: octue
      gcp_service_name: elevations-populator
      gcp_environment: main
      cloud_run_flags: "--ingress=all --allow-unauthenticated --cpu=2 --memory=8Gi --concurrency=5 --max-instances=10"
