name: update-pull-request

on: pull_request

jobs:
  description:
    uses: octue/workflows/.github/workflows/update-pull-request.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
